// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).

// Update API types exposed via contextBridge
import type { UpdateInfo, DownloadProgress } from "./ipc/updater/types";

interface UpdateAPI {
  onUpdateChecking(callback: () => void): () => void;
  onUpdateAvailable(callback: (info: UpdateInfo) => void): () => void;
  onUpdateNotAvailable(callback: (info: UpdateInfo) => void): () => void;
  onUpdateDownloaded(callback: (info: UpdateInfo) => void): () => void;
  onUpdateProgress(callback: (progress: DownloadProgress) => void): () => void;
  onUpdateError(callback: (error: string) => void): () => void;
}

declare global {
  // Vite constants injected by Electron Forge
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string | undefined;
  const MAIN_WINDOW_VITE_NAME: string;

  interface Window {
    updateAPI: UpdateAPI;
  }
}

export {};
